# Invoked by avicap_embed_files at build time.
set(content "// Generated file - do not edit.\n#include <cstddef>\n#include <string_view>\n\nnamespace ${NS} {\nnamespace {\n")
set(table "")
set(idx 0)
foreach(f IN LISTS FILES)
    file(READ "${f}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR nbytes "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Break long lines to keep compilers happy.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
    get_filename_component(name "${f}" NAME)
    string(APPEND content "const unsigned char kData${idx}[] = {\n${bytes}0x00};\n")
    string(APPEND table "    {\"${name}\", kData${idx}, ${nbytes}},\n")
    math(EXPR idx "${idx} + 1")
endforeach()
string(APPEND content "struct Entry { const char* name; const unsigned char* data; std::size_t size; };\n")
string(APPEND content "const Entry kEntries[] = {\n${table}    {nullptr, nullptr, 0}\n};\n} // namespace\n\n")
string(APPEND content "std::string_view find(std::string_view name) {\n    for (const Entry* e = kEntries; e->name; ++e)\n        if (name == e->name) return {reinterpret_cast<const char*>(e->data), e->size};\n    return {};\n}\n\n")
string(APPEND content "std::size_t count() { return sizeof(kEntries) / sizeof(kEntries[0]) - 1; }\n")
string(APPEND content "std::string_view nameAt(std::size_t i) { return kEntries[i].name; }\n} // namespace ${NS}\n")
file(WRITE "${OUT}.tmp" "${content}")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
